site_name: 'Documentaci贸n API Retail'

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

nav:
  - Home: 'index.md'
  - 'Iniciando': 'iniciando.md'
  - 'Estructura del proyecto': 'estructura.md'
  - 'M贸dulos de la API': 'modulos_api.md'
  - 'Login y autenticaic贸n': 'autenticacion.md'
  - 'Documentaci贸n de los endpoints': 'endpoints_openapi.md'
